# Generated by Django 5.2.7 on 2025-10-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumors',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='rumors',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
