# Generated by Django 5.2.7 on 2025-10-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_reply_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Replies'},
        ),
    ]
