# Generated by Django 5.2.7 on 2025-10-22 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='jumlah_asis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='jumlah_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='jumlah_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nama_pemain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='negara',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='sedang_dijual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='umur',
            field=models.IntegerField(default=0),
        ),
        # migrations.AlterField(
        #     model_name='player',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='player',
        #     name='market_value',
        #     field=models.IntegerField(default=0),
        # ),
    ]
