# Generated by Django 5.2.7 on 2025-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_player_name_player_jumlah_asis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
