# Generated by Django 5.2.7 on 2025-10-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.BigIntegerField(default=0),
        ),
    ]
