# Generated by Django 5.2.7 on 2025-10-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_thumbnail'),
        ('player_transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to='main.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to='main.club')),
            ],
        ),
    ]
