# Generated by Django 5.2.7 on 2025-10-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_transaction', '0002_negotiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
