# Generated by Django 5.2.7 on 2025-10-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_player_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestEleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layout', models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2'), ('4-2-3-1', '4-2-3-1')], default='4-3-3', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_slot_data', models.JSONField(blank=True, default=list, null=True)),
                ('fan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_elevens', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(to='main.player')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
