# Generated by Django 5.2.7 on 2025-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_eleven', '0002_club_player_market_value_player_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
