# Generated by Django 5.2.7 on 2025-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_eleven', '0003_player_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.CharField(blank=True, help_text='Nilai pasar pemain', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='URL ke foto profil pemain', null=True),
        ),
    ]
