# Generated by Django 5.2.7 on 2025-10-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_eleven', '0004_alter_player_market_value_alter_player_nationality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='club',
            new_name='current_club',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nama_pemain',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nationality',
            new_name='negara',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='profile_image_url',
            new_name='thumbnail',
        ),
    ]
