# Generated by Django 5.2.7 on 2025-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_eleven', '0005_rename_club_player_current_club_and_more'),
        ('main', '0003_player_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_club',
        ),
        migrations.AlterField(
            model_name='besteleven',
            name='players',
            field=models.ManyToManyField(to='main.player'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
